services:
  webcounter-backend:
    image: ${DOCKER_USERNAME}/ci-cd-webcounter-backend:${RELEASE_TAG}
    environment:
      DB_NAME: countdb
      DB_USER: mary
      DB_PASSWORD: 123456A!
      DB_HOST: webcounter-db
    depends_on:
      - webcounter-db
    networks:
      - webcounter-network
    ports:
      - "5000:5000"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/pressed"]
      interval: 30s
      timeout: 10s
      retries: 3 

  webcounter-frontend:
    image: ${DOCKER_USERNAME}/ci-cd-webcounter-frontend:${RELEASE_TAG}
    depends_on:
      - webcounter-backend
      - webcounter-db
    networks:
      - webcounter-network
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
        
  webcounter-db:
    image: postgres:13
    environment:
      POSTGRES_DB: countdb
      POSTGRES_USER: mary
      POSTGRES_PASSWORD: 123456A!
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webcounter-network
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mary", "-d", "countdb"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  webcounter-network:
    driver: bridge
