name: Web-counter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      # Checkout the source code
      - name: Checkout the source code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set TEST environment variable
        run: echo "TEST=OK" >> $GITHUB_ENV

      # Run fake tests
      - name: Run fake tests
        run: |
          python -m pytest tests.py 

      # Build Docker images for the frontend and backend and tag them with the Git commit SHA
      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend Docker image
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./backend.dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-webcounter-backend:${{ github.sha }}

      # Build and push frontend Docker image
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  
          file: ./frontend.dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-webcounter-frontend:${{ github.sha }}
